env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
overrides: [
  {
    files: [ "*errorDefs.ts"],
    rules: {
      "quotes": "off"
    }
  }
]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - react-hooks
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "@typescript-eslint/no-non-null-assertion": off
settings:
  react:
    version: "detect"
