// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunError = "KotlincNotFound" | "KotlincPermissionDenied" | "UnsupportedPlatform" | { SaveError: string } | { RemoveError: string } | { WaitError: string } | "KillError" | { FailedSpawn: string };