name: 'publish'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install

      - name: Retrieve release title
        env:
          TAG: ${{ github.ref_name }}
        run: |
          echo "RELEASE_TITLE=$(git tag -l --format='%(subject)' $TAG)" >> $GITHUB_OUTPUT
        id: title

      - name: Retrieve release body
        env:
          TAG: ${{ github.ref_name }}
        run: |
          echo "RELEASE_BODY=$(git tag -l --format='%(body)' $TAG)" >> $GITHUB_OUTPUT
        id: body

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ steps.outputs.RELEASE_TITLE }}
          releaseBody: ${{ steps.outputs.RELEASE_BODY }}
